openapi: 3.0.0
info:
  title: Ingestion API
  version: 1.0.0
  description: API for ingesting website analytics events asynchronously.
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /event:
    post:
      summary: Ingest an event
      description: Validates and queues an analytics event for background processing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - site_id
                - event_type
                - path
                - timestamp
              properties:
                site_id:
                  type: string
                  example: site-abc-123
                event_type:
                  type: string
                  example: page_view
                path:
                  type: string
                  example: /pricing
                user_id:
                  type: string
                  example: user-xyz-789
                timestamp:
                  type: string
                  format: date-time
                  example: 2025-11-12T19:30:01Z
      responses:
        "200":
          description: Event successfully queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
              example:
                success: true
                message: Event queued
        "400":
          description: Validation error (e.g., missing required fields)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error (e.g., queue failure)
components:
  schemas: {}
